In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Slice from 1 to 4 : ",arr[1:4])
print("Slice from 2 to End : ",arr[2:])
print("Slice from Start to 3 : ",arr[:3])

Slice from 1 to 4 :  [2 3 4]
Slice from 2 to End :  [3 4 5]
Slice from Start to 3 :  [1 2 3]


In [15]:
unsorted_arr = np.array([5,2,7,1,9,8,3,6,4])
print("Unsorted Array : ",unsorted_arr)

sorted_arr = np.sort(unsorted_arr)
print("Sorted Array : ",sorted_arr)

Unsorted Array :  [5 2 7 1 9 8 3 6 4]
Sorted Array :  [1 2 3 4 5 6 7 8 9]


In [16]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Even Numbers: ",numbers[numbers % 2 == 0])

mask = numbers % 2 == 0
print("The Numbers are : ",numbers[mask])

Even Numbers:  [ 2  4  6  8 10 12 14]
The Numbers are :  [ 2  4  6  8 10 12 14]


# Indexing and Where

In [17]:
group_indicies = [1,3,4]
print("The Numbers are : ",numbers[group_indicies])

where_result = np.where(numbers % 2 == 0)
print("The Numbers are : ",numbers[where_result])
# Same as Mask

The Numbers are :  [2 4 5]
The Numbers are :  [ 2  4  6  8 10 12 14]


In [18]:
condition = np.where(numbers % 2 == 0,"Print This If True","Print This if False")
print("The Numbers are : ",condition)

The Numbers are :  ['Print This if False' 'Print This If True' 'Print This if False'
 'Print This If True' 'Print This if False' 'Print This If True'
 'Print This if False' 'Print This If True' 'Print This if False'
 'Print This If True' 'Print This if False' 'Print This If True'
 'Print This if False' 'Print This If True' 'Print This if False']


In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

arr3 = np.concatenate((arr1,arr2))
print("Concatenated Array : ",arr3)

Concatenated Array :  [ 1  2  3  4  5  6  7  8  9 10]


# Check If Shape is Same or Not

In [20]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,9])
arr3 = np.array([10,11,12,13])

print("Is the shape of arr1 and arr2: ",arr1.shape == arr2.shape)
print("Is the shape of arr1 and arr3: ",arr1.shape == arr3.shape)

Is the shape of arr1 and arr2:  False
Is the shape of arr1 and arr3:  True


In [21]:
# np.vstack() (vertical stack) is used to add a new row at the bottom of the existing original array.
# new_row is the row that will be added.
# original is the existing NumPy array.

arr1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
new_row = np.array([[11,12]])

arr2 = np.vstack((arr1,new_row))
print("Vertical Stack : ",arr2)

Vertical Stack :  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [22]:
# np.hstack() (horizontal stack) is used to add a new row at the bottom of the existing original array.
# new_row is the row that will be added.
# original is the existing NumPy array.

arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
new_col = np.array([[11], [12], [13], [14], [15]])

arr2 = np.hstack((arr1, new_col))
print("Horizontal Stack:\n", arr2)

Horizontal Stack:
 [[ 1  2 11]
 [ 3  4 12]
 [ 5  6 13]
 [ 7  8 14]
 [ 9 10 15]]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# np.delete(array_name, index_to_delete)
deleted = np.delete(arr, 1)

print("Deleted Array : ",deleted)

Deleted Array :  [ 1  3  4  5  6  7  8  9 10]


# Practise

In [36]:
# arr[start:stop:step]
# start: the starting index of the slice.
# stop: the end index of the slice.
# step: the step size of the slice.
arr = np.array([11, 2, 33, 14, 5, 6, 71,4 ,8, 9, 10])

print("Array: ", arr)

# Slice Array 1
sliced_arr1 = arr[0:]
print("Sliced Array 1: ", sliced_arr1)

# Slice Array 2
sliced_arr2 = arr[1:-1]
print("Sliced Array 2: ", sliced_arr2)

# Slice Array 3
sliced_arr3 = arr[::2]
print("Sliced Array 3: ", sliced_arr3)

# Sort The Array
sort_arr = np.sort(arr)
print("Sorted Array: ", sort_arr)

# Even Numbers
even_number = arr[arr % 2 == 0]
print("Even Numbers: ", even_number)

# Odd Numbers
odd_number = arr[arr % 2 != 0]
print("Odd Numbers: ", odd_number)

# Using Mask 
mask = arr % 2 == 0
even_number = arr[mask]
print("Even Numbers: ", even_number)

# Where Function
where_arr = np.where(arr % 2 == 0)
print("Even Numbers: ", arr[where_arr])

# Concatenation of Arrays
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([6, 7, 8, 9, 10])

arr_combined = np.concatenate((arr_1, arr_2))
print("Concatenated Array: ", arr_combined)

# Check if the shape of two arrays are the same
arrA = np.array([1, 2, 3, 4])
arrB = np.array([5, 6, 7, 8, 9])
arrC = np.array([10, 11, 12, 13])

print("Is the shape of arrA and arrB: ", arrA.shape == arrB.shape)
print("Is the shape of arrA and arrC: ", arrA.shape == arrC.shape)

# Horizontal and Vertical Stack
arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
arr2 = np.array([[9, 10]])

arr3 = np.vstack((arr1, arr2))
print("Vertical Stack: \n", arr3)

arr4 = np.array([[12],[34],[56],[78]])
arr5 = np.hstack((arr1, arr4))
print("Horizontal Stack: \n", arr5)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
deleted = np.delete(arr, 4)
print("Deleted Array: ", deleted)

Array:  [11  2 33 14  5  6 71  4  8  9 10]
Sliced Array 1:  [11  2 33 14  5  6 71  4  8  9 10]
Sliced Array 2:  [ 2 33 14  5  6 71  4  8  9]
Sliced Array 3:  [11 33  5 71  8 10]
Sorted Array:  [ 2  4  5  6  8  9 10 11 14 33 71]
Even Numbers:  [ 2 14  6  4  8 10]
Odd Numbers:  [11 33  5 71  9]
Even Numbers:  [ 2 14  6  4  8 10]
Even Numbers:  [ 2 14  6  4  8 10]
Concatenated Array:  [ 1  2  3  4  5  6  7  8  9 10]
Is the shape of arrA and arrB:  False
Is the shape of arrA and arrC:  True
Vertical Stack: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Horizontal Stack: 
 [[ 1  2 12]
 [ 3  4 34]
 [ 5  6 56]
 [ 7  8 78]]
Deleted Array:  [ 1  2  3  4  6  7  8  9 10]
