In [2]:
import numpy as np


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print("Slice from 1 to 4 : ",arr[1:4])
print("Slice from 2 to End : ",arr[2:])
print("Slice from Start to 3 : ",arr[:3])


Slice from Start to 3 :  [1 2 3]
Slice from 2 to End :  [3 4 5]


In [8]:
unsorted_arr = np.array([5,2,7,1,9,8,3,6,4])
print("Unsorted Array : ",unsorted_arr)

sorted_arr = np.sort(unsorted_arr)
print("Sorted Array : ",sorted_arr)

Unsorted Array :  [5 2 7 1 9 8 3 6 4]
Sorted Array :  [1 2 3 4 5 6 7 8 9]


In [14]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Even Numbers: ",numbers[numbers % 2 == 0])

mask = numbers % 2 == 0
print("The Numbers are : ",numbers[mask])

Even Numbers:  [ 2  4  6  8 10 12 14]
The Numbers are :  [ 2  4  6  8 10 12 14]


# Indexing and Where

In [18]:
group_indicies = [1,3,4]
print("The Numbers are : ",numbers[group_indicies])

where_result = np.where(numbers % 2 == 0)
print("The Numbers are : ",numbers[where_result])
# Same as Mask

The Numbers are :  [2 4 5]
The Numbers are :  [ 2  4  6  8 10 12 14]


In [24]:
condition = np.where(numbers % 2 == 0,"Print This If True","Print This if False")
print("The Numbers are : ",condition)

The Numbers are :  ['Print This if False' 'Print This If True' 'Print This if False'
 'Print This If True' 'Print This if False' 'Print This If True'
 'Print This if False' 'Print This If True' 'Print This if False'
 'Print This If True' 'Print This if False' 'Print This If True'
 'Print This if False' 'Print This If True' 'Print This if False']


In [26]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

arr3 = np.concatenate((arr1,arr2))
print("Concatenated Array : ",arr3)

Concatenated Array :  [ 1  2  3  4  5  6  7  8  9 10]


# Check If Shape is Same or Not

In [31]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,9])
arr3 = np.array([10,11,12,13])

print("Is the shape of arr1 and arr2: ",arr1.shape == arr2.shape)
print("Is the shape of arr1 and arr3: ",arr1.shape == arr3.shape)

Is the shape of arr1 and arr2:  False
Is the shape of arr1 and arr3:  True


In [41]:
# np.vstack() (vertical stack) is used to add a new row at the bottom of the existing original array.
# new_row is the row that will be added.
# original is the existing NumPy array.

arr1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
new_row = np.array([[11,12]])

arr2 = np.vstack((arr1,new_row))
print("Vertical Stack : ",arr2)

Vertical Stack :  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [45]:
# np.hstack() (horizontal stack) is used to add a new row at the bottom of the existing original array.
# new_row is the row that will be added.
# original is the existing NumPy array.

arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
new_col = np.array([[11], [12], [13], [14], [15]])

arr2 = np.hstack((arr1, new_col))
print("Horizontal Stack:\n", arr2)

Horizontal Stack:
 [[ 1  2 11]
 [ 3  4 12]
 [ 5  6 13]
 [ 7  8 14]
 [ 9 10 15]]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# np.delete(array_name, index_to_delete)
deleted = np.delete(arr, 1)

print("Deleted Array : ",deleted)

Deleted Array :  [ 1  3  4  5  6  7  8  9 10]
