# Basics of NumPy

In [1]:
import numpy as np


arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## Array Is Comparatively Faster as the size of operation Increases

In [2]:
import time 

list1 = [1, 2, 3, 4, 5]

start = time.time()

# Correcting the loop to iterate within the list bounds
for i in range(len(list1)):
    list1[i] = list1[i] + 2

end = time.time()

print("Time taken for list:", end - start)

Time taken for list: 0.0001575946807861328


In [3]:
import time 

array1 = np.array([1, 2, 3, 4, 5])

start = time.time()

for i in range(len(array1)):
    array1[i] = array1[i] + 2

end = time.time()

print("Time taken for array:", end - start)

Time taken for array: 0.00011610984802246094


In [4]:
# Array Full of Zeros
zeros = np.zeros((3, 4))
print("zeros array: ", zeros)
print("\n")

# Array Full of Ones
ones = np.ones((2, 3))
print("one array: ", ones)
print("\n")

# Array Full of a number
full = np.full((2, 2), 7)
print("full array: ", full)
print("\n")

# Random Array
random = np.random.random((2, 3))
print("random array:", random)
print("\n")

# Sequence Array of Even Numbers
sequence = np.arange(0, 11, 2)
print("even sequnce array: ", sequence)
print("\n")

# Sequence Array of Odd Numbers
sequence = np.arange(1, 12, 2)
print("odd sequnce array: ", sequence)
print("\n")

zeros array:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


one array:  [[1. 1. 1.]
 [1. 1. 1.]]


full array:  [[7 7]
 [7 7]]


random array: [[0.9310059  0.89813012 0.89823788]
 [0.88010708 0.13469583 0.30466969]]


even sequnce array:  [ 0  2  4  6  8 10]


odd sequnce array:  [ 1  3  5  7  9 11]




# Vector, Matrix and Tensor

In [5]:
vector = np.array([1, 2, 3, 4, 5])
print("Vector: ", vector)
print("\n")

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: ", matrix)
print("\n")

tensor = np.array([[1,2], [3,4], [5,6]])
print("Tensor: ", tensor)
print("\n")

Vector:  [1 2 3 4 5]


Matrix:  [[1 2 3]
 [4 5 6]]


Tensor:  [[1 2]
 [3 4]
 [5 6]]




# Array Properties

In [6]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print("Array: ",array)

arr = np.array([[1, 2, 3],[4, 5, 6]])

print("Size: ", arr.size)
print("DType: ", arr.dtype)
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)

Array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Size:  6
DType:  int64
Shape:  (2, 3)
Dimension:  2


In [8]:
arr = np.arange(12)
print("Original array ", arr)
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)
# Making this to a 3x4 matrix 

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)
# Making this to a 1D array

raveled = reshaped.ravel()
print("\n raveled array ", raveled)
# ravel (returns view, instead of copy)

transpose = reshaped.T
print("\n Transposed array ", transpose)
# Transpose of an array

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
