# Basics of NumPy

In [1]:
import numpy as np


arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## Array Is Comparatively Faster as the size of operation Increases

In [2]:
import time 

list1 = [1, 2, 3, 4, 5]

start = time.time()

# Correcting the loop to iterate within the list bounds
for i in range(len(list1)):
    list1[i] = list1[i] + 2

end = time.time()

print("Time taken for list:", end - start)

Time taken for list: 0.0001575946807861328


In [3]:
import time 

array1 = np.array([1, 2, 3, 4, 5])

start = time.time()

for i in range(len(array1)):
    array1[i] = array1[i] + 2

end = time.time()

print("Time taken for array:", end - start)

Time taken for array: 0.00011610984802246094


In [4]:
# Array Full of Zeros
zeros = np.zeros((3, 4))
print("zeros array: ", zeros)
print("\n")

# Array Full of Ones
ones = np.ones((2, 3))
print("one array: ", ones)
print("\n")

# Array Full of a number
full = np.full((2, 2), 7)
print("full array: ", full)
print("\n")

# Random Array
random = np.random.random((2, 3))
print("random array:", random)
print("\n")

# Sequence Array of Even Numbers
sequence = np.arange(0, 11, 2)
print("even sequnce array: ", sequence)
print("\n")

# Sequence Array of Odd Numbers
sequence = np.arange(1, 12, 2)
print("odd sequnce array: ", sequence)
print("\n")

zeros array:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


one array:  [[1. 1. 1.]
 [1. 1. 1.]]


full array:  [[7 7]
 [7 7]]


random array: [[0.9310059  0.89813012 0.89823788]
 [0.88010708 0.13469583 0.30466969]]


even sequnce array:  [ 0  2  4  6  8 10]


odd sequnce array:  [ 1  3  5  7  9 11]




# Vector, Matrix and Tensor

In [5]:
vector = np.array([1, 2, 3, 4, 5])
print("Vector: ", vector)
print("\n")

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: ", matrix)
print("\n")

tensor = np.array([[1,2], [3,4], [5,6]])
print("Tensor: ", tensor)
print("\n")

Vector:  [1 2 3 4 5]


Matrix:  [[1 2 3]
 [4 5 6]]


Tensor:  [[1 2]
 [3 4]
 [5 6]]




# Array Properties

In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print("Array: ",array)

arr = np.array([[1, 2, 3],[4, 5, 6]])

tensor = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

print("Size: ", arr.size)
print("DType: ", arr.dtype)
print("Shape: ", arr.shape)
print("Tensor: ", tensor)
print("Dimension: ", tensor.ndim)

Array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Size:  6
DType:  int64
Shape:  (2, 3)
Dimension:  3
Tensor:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
arr = np.arange(12)
print("Original array ", arr)
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)
# Making this to a 3x4 matrix 

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)
# Making this to a 1D array

raveled = reshaped.ravel()
print("\n raveled array ", raveled)
# ravel (returns view, instead of copy)

transpose = reshaped.T
print("\n Transposed array ", transpose)
# Transpose of an array

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Practise

In [18]:
import numpy as np

# create an array 
arr1 = np.array([1, 2, 3, 4])
print("1D Array:\n", arr1, "\n")

# create a 2D array 
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("2D Array:\n", arr2, "\n")

# create a zero matrix 
zero_mat = np.zeros((3, 4))
print("Zero Matrix:\n", zero_mat, "\n")

# ones matrix
ones_mat = np.ones((3, 4))
print("Ones Matrix:\n", ones_mat, "\n")

# creating a mat with a specific number
full_mat = np.full((3, 4), 5)
print("Full Matrix (filled with 5s):\n", full_mat, "\n")

# creating a random matrix
random_mat = np.random.random((3, 4))
print("Random Matrix:\n", random_mat, "\n")

# another 2D array 
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Custom 2D Array:\n", arr, "\n")

# Print Size
print("Size of arr:", arr.size)

# Print Shape 
print("Shape of arr:", arr.shape)

# Print Data Type
print("Data Type of arr:", arr.dtype)

# Print Dimension 
print("The Dimension of arr:", arr.ndim)

# Make a dummy Array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Shape an array to a 2D matrix
reshaped_arr = arr.reshape(2, 5)
print("2D Matrix: ", reshaped_arr)

# Flatten the 2D matrix
flattened_arr = reshaped_arr.flatten()
print("Flattened Array: ", flattened_arr)

# Dont Create a New Array just a copy 
ravel_arr = arr.ravel()
print("Raveled Array: ", arr)

# Transpose the 2D matrix
transpose_arr = reshaped_arr.T
print("Transposed Array: ", transpose_arr)

1D Array:
 [1 2 3 4] 

2D Array:
 [[1 2 3 4]
 [5 6 7 8]] 

Zero Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Full Matrix (filled with 5s):
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]] 

Random Matrix:
 [[0.67122225 0.03680744 0.72645213 0.04456966]
 [0.47337202 0.4888822  0.46998221 0.15832517]
 [0.54284864 0.61436452 0.07777013 0.94219747]] 

Custom 2D Array:
 [[1 2 3]
 [4 5 6]] 

Size of arr: 6
Shape of arr: (2, 3)
Data Type of arr: int64
The Dimension of arr: 2
2D Matrix:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Flattened Array:  [ 1  2  3  4  5  6  7  8  9 10]
Raveled Array:  [ 1  2  3  4  5  6  7  8  9 10]
Transposed Array:  [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
